// tables
// 餐桌类型
export const FETCH_ALL_TABLE_TYPES = 'FETCH_ALL_TABLE_TYPES';
export const FETCH_PRINTER_LIST_FOR_TABLE = 'FETCH_PRINTER_LIST_FOR_TABLE';
export const FETCH_NEW_TABLE_TYPE_ITEM = 'FETCH_NEW_TABLE_TYPE_ITEM';

// 餐桌区域
export const FETCH_ALL_DINING_AREA = 'FETCH_ALL_DINING_AREA';
export const FETCH__DINING_AREA_SORT_LIST = 'FETCH__DINING_AREA_SORT_LIST';
export const FETCH_DINING_AREA_ITEM = 'FETCH_DINING_AREA_ITEM';
export const FETCH_ALL_TABLE_COLORS = 'FETCH_ALL_TABLE_COLORS';
export const SET_STATE_STATUS = 'SET_STATE_STATUS';
export const SET_STATE_COLOR = 'SET_STATE_COLOR';

// 餐桌管理
export const FETCH_TABLE_MANAGEMENT_LIST = 'FETCH_TABLE_MANAGEMENT_LIST';
export const FETCH_TABLE_MANAGEMENT_SORT_LIST = 'FETCH_TABLE_MANAGEMENT_SORT_LIST';
export const INIT_TABLE_FILTER = 'INIT_TABLE_FILTER';
export const GET_TABLE_TYPE_LIST = 'GET_TABLE_TYPE_LIST';
export const GET_TABLE_AREA_LIST = 'GET_TABLE_AREA_LIST';
export const FETCH_MANAGEMENT_ITEM = 'FETCH_MANAGEMENT_ITEM';
export const SET_SELECTED_TYPE = 'SET_SELECTED_TYPE';
export const SET_SELECTED_AREA = 'SET_SELECTED_AREA';
