// setting
// 打印机
export const FETCH_HOST_LIST = 'FETCH_HOST_LIST';
export const FETCH_HOST_ITEM = 'FETCH_HOST_ITEM';

// 系统选项
export const FETCH_PARAMS_LIST = 'FETCH_PARAMS_LIST';
export const UPDATE_PARAMETER = 'UPDATE_PARAMETER';
export const UPDATE_PARAMETERS = 'UPDATE_PARAMETERS';
export const FETCH_OPEN_PARAMETER_LIST = 'FETCH_OPEN_PARAMETER_LIST';
export const FETCH_AREA_LIST_FOR_OPEN = 'FETCH_AREA_LIST_FOR_OPEN';
export const FETCH_MENU_LIST_FOR_OPEN = 'FETCH_MENU_LIST_FOR_OPEN';
export const FETCH_PAYMENT_FOR_CHANGE = 'FETCH_PAYMENT_FOR_CHANGE';
export const FETCH_PAYMENT_FOR_COUPON = 'FETCH_PAYMENT_FOR_COUPON';
export const FETCH_HOST_LIST_FOR_SYSTEM_OPTIONS = 'FETCH_HOST_LIST_FOR_SYSTEM_OPTIONS';
export const FETCH_PRINTER_LIST_FOR_SYSTEM_OPTIONS = 'FETCH_PRINTER_LIST_FOR_SYSTEM_OPTIONS';
export const CHECK_RESET_SETTING_ENABLE = 'CHECK_RESET_SETTING_ENABLE';
export const CHECK_BILL_SERVICE_ENABLE = 'CHECK_BILL_SERVICE_ENABLE';

// 后厨打印部门
export const FETCH_FOOD_OUT_DEPT_LIST = 'FETCH_FOOD_OUT_DET_LIST';
export const FETCH_FOOD_OUT_DEPT_ITEM = 'FETCH_FOOD_OUT_DET_ITEM';

// 传菜点
export const FETCH_FOOD_PASS_DEPT_LIST = 'FETCH_FOOD_PASS_DEPT_LIST';
export const FETCH_FOOD_PASS_DEPT_ITEM = 'FETCH_FOOD_PASS_DEPT_ITEM';

// 打印机
export const FETCH_PRINTER_LIST = 'FETCH_PRINTER_LIST';
export const FETCH_PRINTER_ITEM = 'FETCH_PRINTER_ITEM';
export const SAVE_PRINTER_ITEM = 'SAVE_PRINTER_ITEM';

// 小票
export const FETCH_REPORT_TEMPLATE_LIST = 'FETCH_REPORT_TEMPLATE_LIST';
export const FETCH_REPORT_LIST = 'FETCH_REPORT_LIST';
export const SET_REPORT_TEMPLATE_ID = 'SET_REPORT_TEMPLATE_ID';
export const UPDATE_REPORT_TEMPLATE = 'UPDATE_REPORT_TEMPLATE';
export const FETCH_REPORT_TEMPLATE_ITEM = 'FETCH_REPORT_TEMPLATE_ITEM';
export const FETCH_SYSTEM_TEMPLATE_LIST = 'FETCH_SYSTEM_TEMPLATE_LIST';
export const CHECK_ADD_OR_EDIT_SYSTEMPLATE = 'CHECK_ADD_OR_EDIT_SYSTEMPLATE';

// 外卖
export const FETCH_TAKEOUT_MAPPING_LIST = 'FETCH_TAKEOUT_MAPPING_LIST';
export const FETCH_VENDOR_LIST = 'FETCH_VENDOR_LIST';
export const FETCH_DISH_LIST = 'FETCH_DISH_LIST';
export const TAKEOUT_LINK = 'TAKEOUT_LINK';
export const FETCH_NO_PAGE_TAKEOUT_LIST = 'FETCH_NO_PAGE_TAKEOUT_LIST';

// 服务费设置
export const FETCH_SERVICE_ITEMS = 'FETCH_SERVICE_ITEMS';
export const FETCH_SERVICE_AREA_LIST = 'FETCH_SERVICE_AREA_LIST';
