// 菜单
export const FETCH_COOK_BOOK_LIST = 'FETCH_COOK_BOOK_LIST';
export const FETCH_COOK_BOOK_ITEM = 'FETCH_COOK_BOOK_ITEM';
export const FETCH_COMPANY_MENU_LIST = 'FETCH_COMPANY_MENU_LIST';
export const FETCH_COMPANY_LINKED_MENU_LIST = 'FETCH_COMPANY_LINKED_MENU_LIST';
export const CHANGE_COOK_VISIBLE = 'CHANGE_COOK_VISIBLE';
export const FETCH_COMPANY_DETAILS = 'FETCH_COMPANY_DETAILS';

// 门店更新管理
// export const FETCH_SHOP_UPDATE_LIST = 'FETCH_SHOP_UPDATE_LIST';
// export const FETCH_SHOP_UPDATE_FORM_DATA = 'FETCH_SHOP_UPDATE_FORM_DATA';
// export const BATCH_UPDATE_COOK_BOOK = 'BATCH_UPDATE_COOK_BOOK';
// export const FETCH_ADD_MENU_AUTHORITY = 'FETCH_ADD_MENU_AUTHORITY';
// export const FETCH_COOK_BOOK_MANAGEMENT_LIST = 'FETCH_COOK_BOOK_MANAGEMENT_LIST';
export const FETCH_COMPANY_DISH_MENU_ITEM = 'FETCH_COMPANY_DISH_MENU_ITEM';
export const FETCH_CONTENT_TYPES = 'API_FETCH_CONTENT_TYPES';
export const SEND_COMPANY_DATAS = 'SEND_COMPANY_DATAS';

// 更新日志
export const FETCH_UPDATE_LOG_LIST = 'FETCH_UPDATE_LOG_LIST';
export const FETCH_UPDATE_LOG_DETAIL = 'FETCH_UPDATE_LOG_DETAIL';
//获取门店菜品数据
export const FETCH_SHOP_DISH_DATA_UPLOAD_LIST = 'FETCH_SHOP_DISH_DATA_UPLOAD_LIST';
