// detail
export const FETCH_RECONCILIATION_SHOP_LIST = 'FETCH_RECONCILIATION_SHOP_LIST';
export const FETCH_RECONCILIATION_DETAIL_LIST = 'FETCH_RECONCILIATION_DETAIL_LIST';
export const FETCH_RECONCILIATION_DETAIL_ITEM = 'FETCH_RECONCILIATION_DETAIL_ITEM';
export const FETCH_RECONCILIATION_USER_LIST = 'FETCH_RECONCILIATION_USER_LIST';
export const FETCH_RECONCILIATION_PAYMENTLIST = 'FETCH_RECONCILIATION_PAYMENTLIST';

// log
export const FETCH_RECONCILIATION_LOG_LIST = 'FETCH_RECONCILIATION_LOG_LIST';
export const REFRESH_RECONCILIATION_LOG_LIST = 'REFRESH_RECONCILIATION_LOG_LIST';
