// 账单
export const FETCH_CHARGEOBJ_LIST = 'FETCH_CHARGEOBJ_LIST';
export const FETCH_CHARGE_LIST = 'FETCH_CHARGE_LIST';
export const API_FETCH_ORDERNO = 'API_FETCH_ORDERNO';
export const API_FETCH_CHARGEBILL_UPDATE = 'API_FETCH_CHARGEBILL_UPDATE';
export const API_FETCH_CHARGEBILLDONE_LIST = 'API_FETCH_CHARGEBILLDONE_LIST';
export const API_FETCH_CHARGECANCEL = 'API_FETCH_CHARGECANCEL';
export const API_FETCH_BILLDETAIL = 'API_FETCH_BILLDETAIL';
export const API_FETCH_BILLLIST = 'API_FETCH_BILLLIST';
export const API_FETCH_BILLLISTBATCH = 'API_FETCH_BILLLISTBATCH';
export const API_FETCH_BILLLISTUPLOAD = 'API_FETCH_BILLLISTUPLOAD';
export const API_FETCH_BILLLISTUPLOADBATCH = 'API_FETCH_BILLLISTUPLOADBATCH';
export const API_FETCH_NEW_BILL_LIST = 'API_FETCH_NEW_BILL_LIST'; //获取自由定义账单列表
export const API_FETCH_NEW_BILL_PROTOCOL_LIST = 'API_FETCH_NEW_BILL_PROTOCOL_LIST'; //获取自由定义账单协议列表

// 账单上传记录
export const API_FETCH_BILL_UPLOAD_LOG_LIST = 'API_FETCH_BILL_UPLOAD_LOG_LIST';
export const API_FETCH_BILL_STATISTICS_TYPE_LIST = 'API_FETCH_BILL_STATISTICS_TYPE_LIST';
export const API_FETCH_BILL_STATISTICS_INCOME = 'API_FETCH_BILL_STATISTICS_INCOME';
