// 公告通知
export const FETCH_SYSTEM_NOTICES_LIST = 'FETCH_SYSTEM_NOTICES_LIST';
export const GET_SYSTEM_NOTICES_DETAIL = 'GET_SYSTEM_NOTICES_DETAIL';
export const DELETE_SYSTEM_NOTICES = 'DELETE_SYSTEM_NOTICES';
