export const FETCH_SYSTEM_REPORT_TEMPLATE_LIST = 'FETCH_SYSTEM_REPORT_TEMPLATE_LIST';
export const FETCH_SYSTEM_REPORT_TYPE_LIST = 'FETCH_SYSTEM_REPORT_TYPE_LIST';
export const FETCH_SYSTEM_REPORT_ATTRIBUTE_LIST = 'FETCH_SYSTEM_REPORT_ATTRIBUTE_LIST';
export const FETCH_SYSTEM_REPORT_TEMPLATE_DATASOURCE = 'FETCH_SYSTEM_REPORT_TEMPLATE_DATASOURCE';
export const FETCH_SYSTEM_REPORT_TEMPLATE_ITEM = 'FETCH_SYSTEM_REPORT_TEMPLATE_ITEM';

export const FETCH_SYSTEM_PRINTER_LIST = 'FETCH_SYSTEM_PRINTER_LIST';
export const FETCH_SYSTEM_PRINTER_TYPE = 'FETCH_SYSTEM_PRINTER_TYPE';

export const FETCH_PRINTER_BUY_ADDRESS = 'FETCH_PRINTER_BUY_ADDRESS';
