// 公司信息
export const SAVE_MANAGE_COMPANY_INFO = 'SAVE_MANAGE_COMPANY_INFO';
export const FETCH_MANAGE_COMPANY_DETAIL = 'FETCH_MANAGE_COMPANY_DETAIL';
export const FETCH_COMPANY_DETAIL = 'FETCH_COMPANY_DETAIL';
