// business
// 营业餐段
export const FETCH_ALL_SHIFT = 'FETCH_ALL_SHIFT';
export const DELETE_SHIFT_BY_ID = 'DELETE_SHIFT_BY_ID';
export const GET_SHIFT_LAST_ID = 'GET_SHIFT_LAST_ID';
export const FETCH_SHIFT_DETAIL = 'FETCH_SHIFT_DETAIL';

// 收银班别
export const FETCH_ALL_CASHIER = 'FETCH_ALL_CASHIER';
export const DELETE_CASHIER_BY_ID = 'DELETE_CASHIER_BY_ID';
export const GET_CASHIER_LAST_ID = 'GET_CASHIER_LAST_ID';
export const FETCH_CASHIER_DETAIL = 'FETCH_CASHIER_DETAIL';

// 销售分类
export const FETCH_ALL_SALES = 'FETCH_ALL_SALES';
export const SAVE_SALES_SUCCESS = 'SAVE_SALES_SUCCESS';
export const UPDATE_SALES_SUCCESS = 'UPDATE_SALES_SUCCESS';
export const DELETE_SALES_BY_ID = 'DELETE_SALES_BY_ID';
export const GET_SALES_LAST_ID = 'GET_SALES_LAST_ID';
export const FETCH_SALES_DETAIL = 'FETCH_SALES_DETAIL';

// 收入分类
export const FETCH_ALL_REVENUE = 'FETCH_ALL_REVENUE';
export const SAVE_REVENUE_SUCCESS = 'SAVE_REVENUE_SUCCESS';
export const UPDATE_REVENUE_SUCCESS = 'UPDATE_REVENUE_SUCCESS';
export const DELETE_REVENUE_BY_ID = 'DELETE_REVENUE_BY_ID';
export const GET_REVENUE_LAST_ID = 'GET_REVENUE_LAST_ID';
export const FETCH_REVENUE_DETAIL = 'FETCH_REVENUE_DETAIL';
export const GET_REVENUE_GROUP_LIST = 'GET_REVENUE_GROUP_LIST';

// 收入分组管理
export const FETCH_REVENUE_GROUP_LIST = 'FETCH_REVENUE_GROUP_LIST';
export const GET_REVENUE_GROUP_DETAIL = 'GET_REVENUE_GROUP_DETAIL';

// 付款方式
export const FETCH_ALL_CREDIT_ACCOUNT = 'FETCH_ALL_CREDIT_ACCOUNT';
export const SAVE_CREDIT_ACCOUNT_SUCCESS = 'SAVE_CREDIT_ACCOUNT_SUCCESS';
export const UPDATE_CREDIT_ACCOUNT_SUCCESS = 'UPDATE_CREDIT_ACCOUNT_SUCCESS';
export const DELETE_CREDIT_ACCOUNT_BY_ID = 'DELETE_CREDIT_ACCOUNT_BY_ID';
export const GET_CREDIT_ACCOUNT_LAST_ID = 'GET_CREDIT_ACCOUNT_LAST_ID';
export const FETCH_CREDIT_ACCOUNT_DETAIL = 'FETCH_CREDIT_ACCOUNT_DETAIL';

// 送餐者
export const FETCH_ALL_DELIVERER = 'FETCH_ALL_DELIVERER';
export const SAVE_DELIVERER_SUCCESS = 'SAVE_DELIVERER_SUCCESS';
export const UPDATE_DELIVERER_SUCCESS = 'UPDATE_DELIVERER_SUCCESS';
export const DELETE_DELIVERER_BY_ID = 'DELETE_DELIVERER_BY_ID';
export const GET_DELIVERER_LAST_ID = 'GET_DELIVERER_LAST_ID';
export const FETCH_DELIVERER_DETAIL = 'FETCH_DELIVERER_DETAIL';

// 订单来源
export const FETCH_ALL_ORDER_SOURCE = 'FETCH_ALL_ORDER_SOURCE';
export const FETCH_SORT_ORDER_SOURCE = 'FETCH_SORT_ORDER_SOURCE';
export const SAVE_ORDER_SOURCE_SUCCESS = 'SAVE_ORDER_SOURCE_SUCCESS';
export const UPDATE_ORDER_SOURCE_SUCCESS = 'UPDATE_ORDER_SOURCE_SUCCESS';
export const DELETE_ORDER_SOURCE_BY_ID = 'DELETE_ORDER_SOURCE_BY_ID';
export const UPDATE_ORDER_SOURCE_SORT = 'UPDATE_ORDER_SOURCE_SORT';
export const GET_ORDER_SOURCE_LAST_ID = 'GET_ORDER_SOURCE_LAST_ID';
export const FETCH_ORDER_SOURCE_DETAIL = 'FETCH_ORDER_SOURCE_DETAIL';

// 付款方式
export const FETCH_ALL_PAYMENT = 'FETCH_ALL_PAYMENT';
export const FETCH_SORT_PAYMENT = 'FETCH_SORT_PAYMENT';
export const SAVE_PAYMENT_SUCCESS = 'SAVE_PAYMENT_SUCCESS';
export const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS';
export const UPDATE_BATCH_PAYMENT_SUCCESS = 'UPDATE_BATCH_PAYMENT_SUCCESS';
export const DELETE_PAYMENT_BY_ID = 'DELETE_PAYMENT_BY_ID';
export const DELETE_PAYMENT_BY_IDS = 'DELETE_PAYMENT_BY_IDS';
export const UPDATE_PAYMENT_SORT = 'UPDATE_PAYMENT_SORT';
export const GET_PAYMENT_LAST_ID = 'GET_PAYMENT_LAST_ID';
export const FETCH_PAYMENT_DETAIL = 'FETCH_PAYMENT_DETAIL';
export const UPDATE_SORT_PAYMENT = 'UPDATE_SORT_PAYMENT';
export const FETCH_SHORTCUT_KEYS = 'FETCH_SHORTCUT_KEYS';

export const FETCH_MW_COUPONS = 'FETCH_MW_COUPONS';
export const FETCH_PAYMENT_TYPES = 'FETCH_PAYMENT_TYPES';
export const FETCH_PAYMENT_TYPES_BY_PAGE = 'FETCH_PAYMENT_TYPES_BY_PAGE';
export const SAVE_PAYMENT_TYPE_SUCCESS = 'SAVE_PAYMENT_TYPE_SUCCESS';
export const UPDATE_PAYMENT_TYPE_SUCCESS = 'UPDATE_PAYMENT_TYPE_SUCCESS';
export const DELETE_PAYMENT_TYPE_BY_ID = 'DELETE_PAYMENT_TYPE_BY_ID';
export const GET_PAYMENT_TYPE_LAST_ID = 'GET_PAYMENT_TYPE_LAST_ID';
export const FETCH_PAYMENT_TYPE_DETAIL = 'FETCH_PAYMENT_TYPE_DETAIL';

// 外卖设置
export const FETCH_TAKEOUT_DETAIL = 'FETCH_TAKEOUT_DETAIL';
export const UPDATE_TAKEOUT_DETAIL = 'UPDATE_TAKEOUT_DETAIL';
