// 菜品要求
export const DISHES_CLEAR_ERROR = 'DISHES_CLEAR_ERROR';
export const FETCH_ALL_EXPLAIN = 'FETCH_ALL_EXPLAIN';
export const SAVE_EXPLAIN_SUCCESS = 'SAVE_EXPLAIN_SUCCESS';
export const UPDATE_EXPLAIN_SUCCESS = 'UPDATE_EXPLAIN_SUCCESS';
export const DELETE_EXPLAIN_BY_ID = 'DELETE_EXPLAIN_BY_ID';
export const DELETE_EXPLAIN_BY_IDS = 'DELETE_EXPLAIN_BY_IDS';
export const GET_EXPLAIN_LAST_ID = 'GET_EXPLAIN_LAST_ID';
export const FETCH_EXPLAIN_DETAIL = 'FETCH_EXPLAIN_DETAIL';
export const FETCH_EXPLAIN_CONTENTS = 'FETCH_EXPLAIN_CONTENTS';
export const SAVE_EXPLAIN_CONTENT = 'SAVE_EXPLAIN_CONTENT';
export const UPDATE_EXPLAIN_CONTENT = 'UPDATE_EXPLAIN_CONTENT';
export const DELETE_EXPLAIN_CONTENT = 'DELETE_EXPLAIN_CONTENT';
export const FETCH_ALL_MENUS = 'FETCH_ALL_MENUS';
export const FETCH_LINKED_MENUS = 'FETCH_LINKED_MENUS';
export const SAVE_EXPLAIN_MENUS = 'SAVE_EXPLAIN_MENUS';
export const FETCH_EXPLAIN_MENUCLS = 'FETCH_EXPLAIN_MENUCLS';

// 菜品分类
export const FETCH_ALL_CLASSIFY = 'FETCH_ALL_CLASSIFY';
export const FETCH_CLASSIFY_BY_PAGE = 'FETCH_CLASSIFY_BY_PAGE';
export const SAVE_CLASSIFY_SUCCESS = 'SAVE_CLASSIFY_SUCCESS';
export const UPDATE_CLASSIFY_SUCCESS = 'UPDATE_CLASSIFY_SUCCESS';
export const DELETE_CLASSIFY_BY_ID = 'DELETE_CLASSIFY_BY_ID';
export const GET_CLASSIFY_LAST_ID = 'GET_CLASSIFY_LAST_ID';
export const FETCH_CLASSIFY_DETAIL = 'FETCH_CLASSIFY_DETAIL';
export const FETCH_EXPCLS_LIST = 'FETCH_EXPCLS_LIST';
export const FETCH_EXPCLS_LIST_BATCH = 'FETCH_EXPCLS_LIST_BATCH'; //批量设置
export const SAVE_EXPCLS_SUCCESS = 'SAVE_EXPCLS_SUCCESS';
export const FETCH_REVENUE_TYPE_LIST = 'FETCH_REVENUE_TYPE_LIST';
export const FETCH_REVENUE_TYPE_LIST_BATCH = 'FETCH_REVENUE_TYPE_LIST_BATCH'; //批量设置
export const SAVE_REVENUE_TYPE_SUCCESS = 'SAVE_REVENUE_TYPE_SUCCESS';

// 菜品
export const FETCH_ALL_MENU = 'FETCH_ALL_MENU';
export const FETCH_MENU_SETTING_LIST = 'FETCH_MENU_SETTING_LIST';
export const FETCH_MENU_SORT_LIST = 'FETCH_MENU_SORT_LIST';
export const UPDATE_MENU_SORT_LIST = 'UPDATE_MENU_SORT_LIST';
export const FETCH_MENU_CLASS_LIST = 'FETCH_MENU_CLASS_LIST';
export const DOWNLOAD_MENU_FILE = 'DOWNLOAD_MENU_FILE';
export const SAVE_MENU_SUCCESS = 'SAVE_MENU_SUCCESS';
export const FETCH_MENU_HELP_CODE = 'FETCH_MENU_HELP_CODE';
export const FETCH_MENU_MAX_ID = 'FETCH_MENU_MAX_ID';
export const FETCH_MENU_PRINT_LIST = 'FETCH_MENU_PRINT_LIST';
export const FETCH_MENU_DETAIL = 'FETCH_MENU_DETAIL';
export const DELETE_MENU_UNIT = 'DELETE_MENU_UNIT';
export const GET_MENU_UPLOAD_RESULT = 'GET_MENU_UPLOAD_RESULT';
export const MENU_EDIT = 'MENU_EDIT';
export const MENU_SAVE = 'MENU_SAVE';

// 菜品打印部门
export const FETCH_ALL_MENU_PRINT = 'FETCH_ALL_MENU_PRINT';
export const UPDATE_MENU_PRINT_SUCCESS = 'UPDATE_MENU_PRINT_SUCCESS';
export const GET_ALL_PRINT_DEPT = 'GET_ALL_PRINT_DEPT';
export const BATCH_UPDATE_PRINT_SUCCESS = 'BATCH_UPDATE_PRINT_SUCCESS';
export const IS_PRINT_PLAN_EXIST = 'IS_PRINT_PLAN_EXIST';
export const SAVE_MENU_PRINT_PLAN = 'SAVE_MENU_PRINT_PLAN';
export const EDIT_MENU_PRINT_PLAN = 'EDIT_MENU_PRINT_PLAN';
export const FETCH_PRINT_PLAN_LIST = 'FETCH_PRINT_PLAN_LIST';
export const GET_PRINT_NAME_LIST = 'GET_PRINT_NAME_LIST';
export const GET_PRINT_PLAN_DETAIL = 'GET_PRINT_PLAN_DETAIL';
export const GET_INIT_PRINT_PLAN_DETAIL = 'GET_INIT_PRINT_PLAN_DETAIL';
export const GET_SET_MEAL_PRINT_DETAIL = 'GET_SET_MEAL_PRINT_DETAIL';
export const SET_ITEM_KIND = 'SET_ITEM_KIND';
export const LIST_PRINT_PLAN_DETAIL = 'LIST_PRINT_PLAN_DETAIL';

// 菜品配料
export const FETCH_ALL_INGRED_LIST = 'FETCH_ALL_INGRED_LIST';
export const DELETE_MENU_INGREDIENT = 'DELETE_MENU_INGREDIENT';
export const FETCH_INGREDIENT_DETAIL = 'FETCH_INGREDIENT_DETAIL';
export const GET_INGREDIENT_GROUPS = 'GET_INGREDIENT_GROUPS';
export const FETCH_INGREDIENT_GROUP_LIST = 'FETCH_INGREDIENT_GROUP_LIST';
export const DELETE_MANAGE_INGREDIENT_GROUP = 'DELETE_MANAGE_INGREDIENT_GROUP';
export const GET_INGREDIENT_GROUP_DETAIL = 'GET_INGREDIENT_GROUP_DETAIL';

// 出售方案
export const FETCH_SELL_PLAN_LIST = 'FETCH_SELL_PLAN_LIST';
export const DELETE_MENU_SELL_PLAN = 'DELETE_MENU_SELL_PLAN';
export const GET_ALL_MAREA = 'GET_ALL_MAREA';
export const GET_ALL_MSECTION = 'GET_ALL_MSECTION';
export const GET_SELL_DAY_LIST = 'GET_SELL_DAY_LIST';
export const GET_SELL_PLAN_DETAIL = 'GET_SELL_PLAN_DETAIL';
export const FETCH_CLASS_LIST_TYPE = 'FETCH_CLASS_LIST_TYPE';

// 套餐
export const FETCH_ALL_SET_MEALS = 'FETCH_ALL_SET_MEALS';
export const FETCH_ALL_SET_MEAL_TREE = 'FETCH_ALL_SET_MEAL_TREE';
export const DELETE_SET_MEALS_SUCCESS = 'DELETE_SET_MEALS_SUCCESS';
export const FETCH_SET_MEAL_DETAIL = 'FETCH_SET_MEAL_DETAIL';
export const FETCH_SET_SIDE_DTL_TREE = 'FETCH_SET_SIDE_DTL_TREE';
export const FETCH_SET_SIDE_DTL_LIST = 'FETCH_SET_SIDE_DTL_LIST';
export const CLEAR_SET_SIDE_DTL_LIST = 'CLEAR_SET_SIDE_DTL_LIST';
export const FETCH_SET_SIDE_DTL_DETAIL = 'FETCH_SET_SIDE_DTL_DETAIL';
export const FETCH_GARNISH_LIST = 'FETCH_GARNISH_LIST';
export const FETCH_SELECTED_GARNISH_LIST = 'FETCH_SELECTED_GARNISH_LIST';
export const FETCH_SET_MEAL_BILL_SPLIT_DETAIL = 'FETCH_SET_MEAL_BILL_SPLIT_DETAIL';
export const FETCH_SET_MEAL_PRINTER_LIST = 'FETCH_SET_MEAL_PRINTER_LIST';
export const FETCH_SET_MEAL_MENUCLS_LIST = 'FETCH_SET_MEAL_MENUCLS_LIST';
export const FETCH_MENU_PICTURE_LIST = 'FETCH_MENU_PICTURE_LIST';

//秒点
export const FETCH_DISH_CLASSIFY_LIST_SP = 'FETCH_DISH_CLASSIFY_LIST_SP'; //菜品分类列表
export const FETCH_SECOND_POINT_LIST = 'FETCH_SECOND_POINT_LIST';   //秒点表格列表
export const FETCH_DISH_REQUIRE_GRP_LIST_SP = 'FETCH_DISH_REQUIRE_GRP_LIST_SP';   //秒点菜品要求分组
export const FETCH_DISH_REQUIRE_SINGLE_LIST_SP = 'FETCH_DISH_REQUIRE_SINGLE_LIST_SP';   //秒点菜品要求单个详细
export const FETCH_DISH_REQUIRE_BATCH_LIST_SP = 'FETCH_DISH_REQUIRE_BATCH_LIST_SP';   //秒点菜品批量详细
