// function detection
export const FETCH_COMPANY_LIST = 'FETCH_COMPANY_LIST';
export const FETCH_SHOP_GROUP_LIST = 'FETCH_SHOP_GROUP_LIST';
export const FETCH_SHOP_LIST = 'FETCH_SHOP_LIST';
export const FETCH_SHOP_DETECTION_TOKEN = 'FETCH_SHOP_DETECTION_TOKEN';
export const FETCH_SHOP_DETECTION_RESULT = 'FETCH_SHOP_DETECTION_RESULT';
export const FETCH_SHOP_CENTRAL_DATA = 'FETCH_SHOP_CENTRAL_DATA';

// 灰度发布
export const FETCH_GATED_LAUNCH_LIST = 'FETCH_GATED_LAUNCH_LIST';
export const DELETE_GATED_LAUNCH = 'DELETE_GATED_LAUNCH';

// 终端管理 概况
export const FETCH_TERMINAL_SUMMARY = 'FETCH_TERMINAL_SUMMARY';
export const FETCH_TERMINAL_VERSION_LIST = 'FETCH_TERMINAL_VERSION_LIST';
export const FETCH_TERMINAL_LIST = 'FETCH_TERMINAL_LIST';

// 版本升级
export const FETCH_UPGRADED_ETAIL = 'FETCH_UPGRADED_ETAIL';
export const FETCH_UPGRADE_LIST = 'FETCH_UPGRADE_LIST';

// 软件类型
export const FETCH_PUBLISH_LIST = 'FETCH_PUBLISH_LIST';
export const FETCH_PUBLISH_DETAIL = 'FETCH_PUBLISH_DETAIL';

// 软件类型
export const FETCH_SOFTWARE_LIST = 'FETCH_SOFTWARE_LIST';
export const FETCH_SOFTWARE_DETAIL = 'FETCH_SOFTWARE_DETAIL';
