// 门店列表
export const FETCH_MANAGE_SHOP_LIST = 'FETCH_MANAGE_SHOP_LIST';
export const GET_SHOP_GROUP_TYPES = 'GET_SHOP_GROUP_TYPES';
export const FETCH_MANAGE_SHOP_DETAIL = 'FETCH_MANAGE_SHOP_DETAIL';
export const UPDATE_MANAGE_SHOP_INFO = 'UPDATE_MANAGE_SHOP_INFO';
export const GET_UPDATE_SHOP_MESSAGE = 'GET_UPDATE_SHOP_MESSAGE';
export const FETCH_SHOP_TREE = 'FETCH_SHOP_TREE';
export const ADD_SHOP_TREE_GROUP_NODE = 'ADD_SHOP_TREE_GROUP_NODE';

// 连锁标准化列表
export const FETCH_CHAINS_SETTINGS = 'FETCH_CHAINS_SETTINGS';

// ERP系统对接
export const FETCH_ERP_SYSTEM_INTEGRATION_LIST = 'FETCH_ERP_SYSTEM_INTEGRATION_LIST';

// 门店分组
export const GET_SHOP_GROUP_LIST = 'GET_SHOP_GROUP_LIST';
export const GET_SHOP_GROUP_DETAIL = 'GET_SHOP_GROUP_DETAIL';
export const UPDATE_MANAGE_SHOP_GROUP = 'UPDATE_MANAGE_SHOP_GROUP';
export const GET_ALL_SHOP_LIST = 'GET_ALL_SHOP_LIST';
