export const FETCH_ALL_BACK_REASON = 'FETCH_ALL_BACK_REASON';
export const FETCH_ALL_BACK_REASON_WITHOUT_PAGE = 'FETCH_ALL_BACK_REASON_WITHOUT_PAGE';
export const FETCH_BACK_REASON_DETAIL = 'FETCH_BACK_REASON_DETAIL';
export const SAVE_BACK_REASON = 'SAVE_BACK_REASON';
export const UPDATE_BACK_REASON = 'UPDATE_BACK_REASON';
export const DELETE_BACK_REASON_BY_ID = 'DELETE_BACK_REASON_BY_ID';

export const FETCH_ALL_GIFT_REASON = 'FETCH_ALL_GIFT_REASON';
export const FETCH_GIFT_REASON_DETAIL = 'FETCH_GIFT_REASON_DETAIL';
export const SAVE_GIFT_REASON = 'SAVE_GIFT_REASON';
export const UPDATE_GIFT_REASON = 'UPDATE_GIFT_REASON';
export const DELETE_GIFT_REASON_BY_ID = 'DELETE_GIFT_REASON_BY_ID';

export const FETCH_ALL_DISCOUNT_REASON = 'FETCH_ALL_DISCOUNT_REASON';
export const FETCH_DISCOUNT_REASON_DETAIL = 'FETCH_DISCOUNT_REASON_DETAIL';
export const SAVE_DISCOUNT_REASON = 'SAVE_DISCOUNT_REASON';
export const UPDATE_DISCOUNT_REASON = 'UPDATE_DISCOUNT_REASON';
export const DELETE_DISCOUNT_REASON_BY_ID = 'DELETE_DISCOUNT_REASON_BY_ID';

export const FETCH_ALL_RECHEC_REASON = 'FETCH_ALL_RECHEC_REASON';
export const FETCH_RECHEC_REASON_DETAIL = 'FETCH_RECHEC_REASON_DETAIL';
export const SAVE_RECHEC_REASON = 'SAVE_RECHEC_REASON';
export const UPDATE_RECHEC_REASON = 'UPDATE_RECHEC_REASON';
export const DELETE_RECHEC_REASON_BY_ID = 'DELETE_RECHEC_REASON_BY_ID';

export const FETCH_ALL_DELIVERY_NOTE = 'FETCH_ALL_DELIVERY_NOTE';
export const FETCH_DELIVERY_NOTE_DETAIL = 'FETCH_DELIVERY_NOTE_DETAIL';
export const SAVE_DELIVERY_NOTE = 'SAVE_DELIVERY_NOTE';
export const UPDATE_DELIVERY_NOTE = 'UPDATE_DELIVERY_NOTE';
export const DELETE_DELIVERY_NOTE_BY_ID = 'DELETE_DELIVERY_NOTE_BY_ID';

export const FETCH_ALL_BILL_NOTE = 'FETCH_ALL_BILL_NOTE';
export const FETCH_BILL_NOTE_DETAIL = 'FETCH_BILL_NOTE_DETAIL';
export const SAVE_BILL_NOTE = 'SAVE_BILL_NOTE';
export const UPDATE_BILL_NOTE = 'UPDATE_BILL_NOTE';
export const DELETE_BILL_NOTE_BY_ID = 'DELETE_BILL_NOTE_BY_ID';

export const FETCH_ALL_ORDER_UINT = 'FETCH_ALL_ORDER_UINT';
export const FETCH_ALL_ORDER_UINT_LIST = 'FETCH_ALL_ORDER_UINT_LIST';
export const FETCH_ORDER_UINT_DETAIL = 'FETCH_ORDER_UINT_DETAIL';
export const SAVE_ORDER_UINT = 'SAVE_ORDER_UINT';
export const UPDATE_ORDER_UINT = 'UPDATE_ORDER_UINT';
export const DELETE_ORDER_UINT_BY_ID = 'DELETE_ORDER_UINT_BY_ID';
