// 用户日志
export const FETCH_ALL_USER_LOG = 'FETCH_ALL_USER_LOG';
export const FETCH_ALL_USER_OPERATION = 'FETCH_ALL_USER_OPERATION';

// 指纹权限操作
export const FETCH_FINGER_PRINT_LIST = 'FETCH_FINGER_PRINT_LIST';
export const GET_MANAGERS_FINGER_LIST = 'GET_MANAGERS_FINGER_LIST';
export const GET_SHOP_SUPER_FINGER_LIST = 'GET_SHOP_SUPER_FINGER_LIST';

// 部门
export const FETCH_SHOP_DEPARTMENT_LIST = 'FETCH_SHOP_DEPARTMENT_LIST';
export const GET_SHOP_DEPT_DETAIL = 'GET_SHOP_DEPT_DETAIL';

// 用户
export const FETCH_SHOP_USER_LIST = 'FETCH_SHOP_USER_LIST';
export const GET_SHOP_USER_DETAIL = 'GET_SHOP_USER_DETAIL';
export const FETCH_DISCOUNT_PLAN_LIST = 'FETCH_DISCOUNT_PLAN_LIST';

// 用户权限
export const FETCH_SHOP_ROLE_LIST = 'FETCH_SHOP_ROLE_LIST';
export const GET_SHOP_ROLE_DETAIL = 'GET_SHOP_ROLE_DETAIL';
export const GET_SHOP_ROLE_INFO = 'GET_SHOP_ROLE_INFO';
