// 会员价管理
export const API_DISHES_GETVIPLEVELS = 'API_DISHES_GETVIPLEVELS';
export const API_DISHES_GETVIPLIST = 'API_DISHES_GETVIPLIST';
export const API_GET_VIP_ITEM = 'API_GET_VIP_ITEM';
export const API_DISHES_UPDATEVIPPRICE = 'API_DISHES_UPDATEVIPPRICE';
export const API_DISHES_BASHSETVIPBARGAINS = 'API_DISHES_BASHSETVIPBARGAINS';
export const API_GET_CARD_LIST = 'API_GET_CARD_LIST';
export const API_GET_LEVEL_BY_CARD = 'API_GET_LEVEL_BY_CARD';
export const GET_ALL_CARDS_LEVEL = 'GET_ALL_CARDS_LEVEL';
export const GET_COMPANY_ALL_CARDS_LEVEL = 'GET_COMPANY_ALL_CARDS_LEVEL';

// 菜品买减
export const FETCH_BUY_GIFT_LIST = 'FETCH_BUY_GIFT_LIST';
export const FETCH_BARGAIN_MENUS = 'FETCH_BARGAIN_MENUS';
export const FETCH_BARGAIN_TREES = 'FETCH_BARGAIN_TREES';
export const GET_BUY_GIFT_MAXID = 'GET_BUY_GIFT_MAXID';
export const GET_BUY_GIFT_DETAIL = 'GET_BUY_GIFT_DETAIL';

// 菜品特价
export const FETCH_BARGAIN_SALE_LIST = 'FETCH_BARGAIN_SALE_LIST';

// 金额满减
export const FETCH_BARGAIN_FULL_LIST = 'FETCH_BARGAIN_FULL_LIST';
export const DELETE_BARGAIN_FULL_SUCCESS = 'DELETE_BARGAIN_FULL_SUCCESS';
export const UPDATE_BARGAIN_FULL_SUCCESS = 'UPDATE_BARGAIN_FULL_SUCCESS';
export const FETCH_BARGAIN_FULL_DETAIL = 'FETCH_BARGAIN_FULL_DETAIL';
export const GET_CUT_PAYMENTS_LIST = 'GET_CUT_PAYMENTS_LIST';
export const GET_BARGAIN_MAX_ID = 'GET_BARGAIN_MAX_ID';
export const FETCH_BARGAIN_SALE_DETAIL = 'FETCH_BARGAIN_SALE_DETAIL';
export const DELETE_BARGAIN_SALE = 'DELETE_BARGAIN_SALE';
export const UPDATE_BARGAIN_SALE = 'UPDATE_BARGAIN_SALE';
export const UPDATE_LINKED_MENUS = 'UPDATE_LINKED_MENUS';
export const FETCH_BARGAIN_FULL_LINKED_MENUS = 'FETCH_BARGAIN_FULL_LINKED_MENUS';

// 折扣方案
export const FETCH_DISCOUNT_SCHEME_LIST = 'FETCH_DISCOUNT_SCHEME_LIST';
export const FETCH_ALLOWED_USER_LIST = 'FETCH_ALLOWED_USER_LIST';
export const FETCH_DISCOUNT_SCHEME_DETAIL = 'FETCH_DISCOUNT_SCHEME_DETAIL';
export const FETCH_MAX_DISCOUNT_SCHEME_ID = 'FETCH_MAX_DISCOUNT_SCHEME_ID';
export const BATCH_UPDATE_DISCOUNT_RATE = 'BATCH_UPDATE_DISCOUNT_RATE';
export const FETCH_DISCOUNT_SCHEME_COPY_LIST = 'FETCH_DISCOUNT_SCHEME_COPY_LIST';
export const FETCH_DISCOUNT_MENU_CLS_LIST = 'FETCH_DISCOUNT_MENU_CLS_LIST';
export const FETCH_DISCOUNT_LINKED_MENUS = 'FETCH_DISCOUNT_LINKED_MENUS';

