// 销售分类
export const FETCH_ALL_COMPANY_SALES = 'FETCH_ALL_COMPANY_SALES';
export const GET_COMPANY_SALES_LAST_ID = 'GET_COMPANY_SALES_LAST_ID';
export const FETCH_COMPANY_SALES_DETAIL = 'FETCH_COMPANY_SALES_DETAIL';

// 收入分类
export const FETCH_ALL_COMPANY_REVENUE = 'FETCH_ALL_COMPANY_REVENUE';
export const GET_COMPANY_REVENUE_LAST_ID = 'GET_COMPANY_REVENUE_LAST_ID';
export const FETCH_COMPANY_REVENUE_DETAIL = 'FETCH_COMPANY_REVENUE_DETAIL';
