// 第三方对接
export const FETCH_THIRD_PARTY_INTERFACE_LIST = 'FETCH_THIRD_PARTY_INTERFACE_LIST';
export const FETCH_INTERFACE_TYPE_WITHOUT_PAGINATION = 'FETCH_INTERFACE_TYPE_WITHOUT_PAGINATION';
export const FETCH_SHOP_DATASOURCE = 'FETCH_SHOP_DATASOURCE';
export const FETCH_THIRD_PARTY_INTERFACE_ITEM = 'FETCH_THIRD_PARTY_INTERFACE_ITEM';

// 接口类型
export const FETCH_INTERFACE_TYPE_LIST = 'FETCH_INTERFACE_TYPE_LIST';
export const FETCH_INTERFACE_TYPE_ITEM = 'FETCH_INTERFACE_TYPE_ITEM';
